name: 'Push Gem to GPR'
description: 'Push Gem to GitHub Packages Registry'
inputs:
  language:
    description: 'plugin language: java or ruby'
    required: true
    default: ruby
  gem-path:
    description: 'gem path to publish (may be "./build/gems/*.gem" for jruby or "./pkg/*.gem" for ruby)'
    required: true
    default: './pkg/*.gem'
  github-token:
    description: 'please set secrets.GITHUB_TOKEN from your workflow YAML to publish gem to GPR'
    required: true
runs:
  using: "composite"
  steps:
    - if: ${{ inputs.language == 'ruby' && startsWith( github.ref, 'refs/heads/' )}}
      name: Add branch suffix to version
      env:
        REF: ${{ github.ref }}
      run: |
        commit_hash="$(echo ${GITHUB_SHA:0:7})"
        sed -ie "s/\(spec\.version = \"[^\"]\+\)/\1.${commit_hash}.pre/g" *.gemspec
        grep spec.version *.gemspec
      shell: bash
    - if: ${{ inputs.language == 'ruby' }}
      name: Build gem with ruby
      run: rake build
      shell: bash
    - if: ${{ inputs.language == 'java' }}
      name: Build gem with Java
      run: |
        ./gradlew printVersion
        ./gradlew gem
      shell: bash
    - name: Publish to GPR
      env:
        GEM_HOST_API_KEY: "Bearer ${{ inputs.github-token }}"
        OWNER: ${{ github.repository_owner }}
      run: |
        mkdir -p "$HOME/.gem"
        touch "$HOME/.gem/credentials"
        chmod 0600 "$HOME/.gem/credentials"
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push --KEY github --host "https://rubygems.pkg.github.com/${OWNER}" ${{ inputs.gem-path }}
      shell: bash
